# https://github.com/hashicorp/setup-packer
name: packer

on:
  - push

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`

      - name: Run `packer init`
        id: init
        run: "packer init ./packer.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build ./packer.pkr.hcl"
